version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      docker_layer_caching: false
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: echo "Do some things"
      - run: |
          sudo apt update \
          && sudo apt-get install -yq \
          libnss3 \
          libatspi2.0-0 \
          libatk-bridge2.0-0 \
          libcupsfilters1 \
          libxkbcommon0 \
          libasound2 \
          libxshmfence1 \
          libxrandr2 \
          libgbm1 \
          libxcomposite1 \
          libxdamage1
      - run: |
          docker login -u "kunal777" -p "Welcome@77"
      - run: |
          docker build \
            -t kunal777/puppeteer \
            .
      - run: |
          docker push kunal777/puppeteer