version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      docker_layer_caching: false
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: echo "Do some things"
      - run: |
          sudo apt-get update \
          && apt-get install -yq \
          libnss3 \
          libnssutil3 \
          libsmime3 \
          libnspr4 \
          libatk-1.0 \
          libatk-bridge-2.0-0 \
          libcups2 \
          libdrm2 \
          libdbus-1-3 \
          libxkbcommon \
          libXcomposite1 \
          libXdamage1 \
          libXfixes3 \
          libXrandr2 \
          libgbm1 \
          libasound2 \
          libatspi \
          libxshmfence1

          gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
          libexpat1 libfontconfig1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
          libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 \
          libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
          fonts-liberation libappindicator1  lsb-release xdg-utils wget
      - run: |
          docker login -u "kunal777" -p "Welcome@77"
      - run: |
          docker build \
            -t kunal777/puppeteer \
            .
      - run: |
          docker push kunal777/puppeteer