version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      docker_layer_caching: false
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: echo "Do some things"
      - run: |
          apt-get update \
          && apt-get install -yq \
          libnss3 \
          libnssutil3 \
          libsmime3 \
          libnspr4 \
          libatk-1.0 \
          libatk-bridge-2.0-0 \
          libcups2 \
          libdrm2 \
          libdbus-1-3 \
          libxkbcommon \
          libXcomposite1 \
          libXdamage1 \
          libXfixes3 \
          libXrandr2 \
          libgbm1 \
          libasound2 \
          libatspi \
          libxshmfence1
      - run: |
          docker login -u "kunal777" -p "Welcome@77"
      - run: |
          docker build \
            -t kunal777/puppeteer \
            .
      - run: |
          docker push kunal777/puppeteer