version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: echo "Do some things"
      - run: |
          docker login -u "kunal777" -p "Welcome@77"
      - run: |
          docker build \
            -t kunal777/puppeteer \
            .
      - run: |
          docker push kunal777/puppeteer